import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="w-full h-[4rem] justify-center items-center">
          <div>BrandName</div>
        </div>
        <div className="flex w-full h-full bg-green-00">
          <div className="w-[15rem] h-[100vh] bg-gray-800 p-10">
            <div>
              <p>logo</p>
              <p>Brand Name</p>
            </div> */}

        {/* </div>
          <div> */}
        {children}
        {/* </div> */}
        {/* </div> */}
      </body>
    </html>
  );
}
